### ISSUE TITLE
Upgrade Rusqlite to version 0.29

### ISSUE THREAD

**Issue by Ummon** [ivanceras/r2d2-sqlite#52]
A new version of Rusqlite has been released: 0.29

**Comment by felipelalli** [comment]
The error you're seeing is due to conflicting versions of the libsqlite3-sys crate that are being pulled in by different versions of rusqlite. This is a known issue in Rust when two crates in the same dependency graph link to the same native library, but with different versions.

The r2d2_sqlite crate is depending on rusqlite version 0.28.0, which in turn depends on libsqlite3-sys version 0.25.0. But your project is directly depending on rusqlite version 0.29.0, which depends on libsqlite3-sys version 0.26.0. This is causing a conflict because only one version of a native library can be linked.

**Comment by felipelalli** [comment]
Related: #50 #51

**Comment by jerebtw** [comment]
@ivanceras can you please release a new version to cargo to fix this issue

**Comment by antimora** [comment]
Since the fix has been merged, can we have an updated release? The main branch version says it's the 0.21.0 which is released but does not have this fix. Thank you!

**Comment by ivanceras** [comment]
@jerebtw you can publish a new version to crates.io. Logging to crates.io is done via github oauth.
Notice that the previous [releases](https://crates.io/crates/r2d2_sqlite/versions) by Hugo, which I added him as a collaborator. I supposed he is also busy with other things.

```sh
cargo login
cd r2d2-sqlite && cargo publish
```

**Comment by jerebtw** [comment]
> @jerebtw you can publish a new version to crates.io. Logging to crates.io is done via github oauth. Notice that the previous [releases](https://crates.io/crates/r2d2_sqlite/versions) by Hugo, which I added him as a collaborator. I supposed he is also busy with other things.
> 
> ```shell
> cargo login
> cd r2d2-sqlite && cargo publish
> ```

Doesn't work (i think you need to add me on https://crates.io/crates/r2d2_sqlite/settings)

**Comment by ivanceras** [comment]
Ah, I forgot that I have to do that too. I already sent an invite.

**Comment by jerebtw** [comment]
Fixed in version 0.22.0
